### ISSUE TITLE
How to get user's status

### ISSUE THREAD

**Issue by kitsunen** [BundledSticksInkorperated/Discore#11]
Hi!

I'm trying to iterate through a list, trying to find offline members in the said list.
I can't for the life of me think of the right way to fetch one user's current status! :)

![image](https://cloud.githubusercontent.com/assets/6533970/26275763/2d5c22ee-3d71-11e7-8bfd-a8cb7335de00.png)

As you can see from the picture, I should be able to bind "member" to a specific user. What I'm missing is getting the status of that specific user.

The server is big enough to be considered large, hence not showing offline members automatically.
Should I be doing something with Gateway.RequestGuildMembersAsync?

**Comment by Francessco121** [comment]
This may be a little tricky because the guild is considered large.

The way the Discord API works is, for every member in a guild, the API sends a "presence update" for that member. Discore takes these details and stores them on the member's `DiscoreMemberCache` object.

So to get the presence you need to know the guild ID to get the `DiscoreMemberCache` object, for example:
```csharp
DiscoreGuildCache guildCache = cache.Guilds[guildId];
DiscoreMemberCache memberCache = guildCache.Members[userId];

DiscordUserPresence presence = memberCache.Presence;
```

However, the `DiscoreMemberCache` instance will only be available if that member is cached, and the `DiscordUserPresence` instance will be `null` until the member changes their state to warrant an update from the API, or they were available upon the shard starting.

In Discore 2.x, this is a bit of an issue since if the member isn't cached and a presence update is received,  the data will be dropped. The best option for right now would be to call `RequestGuildMembersAsync` right after the guild is available to ensure all the members are in the cache. Any members that join after that call will be automatically cached. If this is done, then every member that received presence data from the API will have their `DiscordUserPresence` data available, and if this is `null` then it is safe to assume that they are offline since the guild is "large".

Sorry this is a bit of a pain currently, I can promise you now that this will be simpler in 3.0.

**Comment by kitsunen** [comment]
No need to be sorry, on the contrary I have had plenty of fun using Discore :)!
I will use this approach, but I have a failsafe as well by using a timer (users have a certain amount of time to react to announce, after which they will get dropped from a list) 

Thanks for the detailed answer!

**Comment by Francessco121** [comment]
Sounds good, feel free to reopen if you run into any problems. :)
