### ISSUE TITLE
Does not transmit sound.

### ISSUE THREAD

**Issue by SunnyElite** [BundledSticksInkorperated/Discore#19]
> Hi, I have a problem, my bot does not transmit sound.
> I'm sleepy, maybe I'm dulling a little.

![rxzvl90ktyceo5909nzwww](https://user-images.githubusercontent.com/28116659/28751986-63e10a08-751d-11e7-9091-f0075331011c.png)

Code - https://hastebin.com/ikafisaziq.cs

**Comment by Francessco121** [comment]
That code definitely looks like it should work... I've been having some really bizzare issues with the voice API recently as well so I have a few questions:

1. What version of Discore are you using?
2. Have you tried changing the server's voice region? (I'm not saying this is a legit fix, but certain voice regions had this issue for me)
3. Did this code previously work?

If you're having the same issue I am, it seems to be related to the version of the voice API Discore uses as well as certain voice servers. If you are using 3.x, I would give the [bug/voice-fixes](https://github.com/BundledSticksInkorperated/Discore/tree/bug/voice-fixes) branch a try. It contains work in progress support for the latest version of the Discord voice API.

Another weird side-effect I've noticed is that when voice data is currently being sent (but no audio is actually going across), all users in the server can't hear each other...

**Comment by SunnyElite** [comment]
1 -
![screenshot_1](https://user-images.githubusercontent.com/28116659/28809483-5fc0f832-768c-11e7-9a4a-4e661fc2fbfa.png)
2 - voice region - In terms of the location of the server?
3 - I do not know, I use your library for the first time, I wrote everything, everything works, but voice does not want.

**Comment by SunnyElite** [comment]
Is there a Nuget or Myget on the branchs?

**Comment by Francessco121** [comment]
> voice region - In terms of the location of the server?

I'm talking about the server option here:
![](https://i.imgur.com/ciEsfSL.png)

I've noticed for example that US East will have weird issues, but US Central won't.

> Is there a Nuget or Myget on the branchs?

Since that branch is still a work in progress, not yet. You should be able to just clone the branch, add the project file to your solution, and swap the NuGet reference with the project ref.

----------

So, when you let your code run, does the loop get stuck from the call to `Connection.CanSendVoiceData(transferBuffer.Length)`, or does it actually send all of the voice data but you just can't hear it? If it's the latter case, then ffmpeg isn't the problem, the socket is functioning, and that WIP branch will probably do the trick for now.

The Discord developers have just recently documented more of the voice API (and coincidentally looks like they partially broke v1 of the voice API), so in v3.1.0 Discore will support the latest voice API version which *should* solve the issue you're having. I'm planning on releasing that this weekend which will contain the fixes from that branch.

**Comment by SunnyElite** [comment]
Yes, the sound seems to be transmitted, but it's not audible, okay, I'll wait for the general branch, I'm too lazy to configure GitHub for Visual Studio: D I hope it does not take long. :)

**Comment by SunnyElite** [comment]
Server Region - The server is in Russia.

**Comment by Francessco121** [comment]
Wait so, you do hear *something*? Is it just messed up sounds spaced out over a few seconds, or just constant screwed up sound? The former is what I get on certain voice regions.

Out of curiosity, I would try and change the server to like US Central or really anything else and see if you get different results.

Also you shouldn't need to link GitHub and VS, just clone it down via CLI or something like GitKraken. Through VS you should be able to do "Add existing project" and just select Discore's .csproj.

**Comment by SunnyElite** [comment]
![hgfdhgfdhgfd](https://user-images.githubusercontent.com/28116659/28917424-4673dde0-784e-11e7-8f3f-aaded560f8b5.png)
What is the problem?

**Comment by Francessco121** [comment]
It looks like VS isn't building Discore, unless there's an inner exception with more details? 

You removed the NuGet reference right?

How did you add the project?
The way I do it is:
1. Right click on solution in solution explorer -> Add -> Existing project...
2. Right click on Dependencies under my bot's project -> Add reference...
3. Select the projects tab on the left (which should be default) and check off Discore on the right

The only other thing I can think of is maybe the solution config got messed up. Try opening up the Configuration Manager (Build -> Configuration Manager...) and make sure that your bot and Discore have matching platforms and are both checked off to build.

If all else fails, try restarting VS then clean and rebuild the solution...?

**Comment by Flex1337** [comment]
Yes, I do everything as you do, but the build with Nuget works. 3.1.0 does not work.

**Comment by Francessco121** [comment]
VS is definitely not building Discore then, try building Discore specifically, then running again.

Also, I think Discore is set to build in 64-bit mode by default... If your bot isn't, it may be looking in the wrong folder under bin/Debug for Discore.dll.

**Comment by Francessco121** [comment]
@Flex1337 Sorry, I thought you were @SunnyElite in my last comment lol... 

If neither of you can get the branch to work, could one of you send me an example project with the audio issue? That may make life a little easier here...

**Comment by SunnyElite** [comment]
One friend's account, but it's all me :D

**Comment by Francessco121** [comment]
So...unfortunately I cannot bring stable voice API v3 support to Discore this weekend. According to the devs, v3 is not ready until the PR for its documentation is merged over at https://github.com/hammerandchisel/discord-api-docs.

Assuming that your code is correct (which is certainly looks to be), the only "fix" for this issue as of now is to change your server to a different voice region.

The actual fix will be included in Discore v4.0.0 (since it's going to change some public API stuff) and can be tracked at #22 .

You can still use the bug/voice-fixes branch if you would like to, but it's proven to still be buggy even though it works in *most* voice regions now...

**Comment by Francessco121** [comment]
Have you had any luck with this recently? I've noticed that my bot is now working fine on us-east servers.

**Comment by Francessco121** [comment]
Going to close this for now since there's no identifiable cause. Discore 4's support for the newest voice API seems to be working fine and will likely fix this once it's done anyway.
