### ISSUE TITLE
Again does not transmit sound.

### ISSUE THREAD

**Issue by SunnyElite** [BundledSticksInkorperated/Discore#30]
Hi, again the bot does not want to transmit the sound.
ffmpeg works, everything seems to be as good, but at the same time nothing is heard in the discord.
![image](https://user-images.githubusercontent.com/28116659/31312493-35d2f43c-abcd-11e7-8113-f7bd403fa501.png)

> https://hastebin.com/urapehecin.cs - Code.

Maybe there is some kind of working example?
I've already checked everything 5 times, even by the old recommendations I changed the server's location.

**Comment by Francessco121** [comment]
Hey, I apologize for the hard time you're having with Discore. I definitely can make a sample for sending audio, but I can almost guarantee that it won't work (at least not a v3 version). I've started investigating (again) why Discore seems to not work with most voice servers and I've been puzzled by it since this started happening earlier this year.

Fixing this issue requires a lot of changes made in v4, so I'm not sure I'll be able to fix the v3 branch. So what I can do is release a pre-release of v4 (which in my testing is actually very stable) that contains all of the voice fixes I've attempted until now, and then make a sample bot for you based on that release. If the sample does not work for you then your issue is certainly the same that I'm investigating.

I'll comment back here soon when I have that ready.

**Comment by Francessco121** [comment]
Okay, give this sample a try: https://github.com/BundledSticksInkorperated/Discore.Samples/tree/master/v4.0.0-pre1/Discore.Samples.VoiceSending. 

The README explains how to setup and use it.

Works for me when connected to the US central voice region.

**Comment by Francessco121** [comment]
So I finally figured out why Discore wasn't working in a lot of voice regions, that is all good and fixed on v4.0.0-pre2. I updated the link in the previous comment, that example should 100% work for you on any voice region. :D

I'll be making a patch for the 3.x branch soon as well as porting those samples to 3.x since 4.0 isn't quite ready yet.

**Comment by Francessco121** [comment]
Here's the v3.1.2 sample for voice sending: https://github.com/BundledSticksInkorperated/Discore.Samples/tree/master/v3.1.2/Discore.Samples.VoiceSending

**Comment by SunnyElite** [comment]
Yes, updated to v4.0.0-pre2, it works, thanks :)
