### ISSUE TITLE
Async Methods

### ISSUE THREAD

**Issue by fedoranimus** [BundledSticksInkorperated/Discore#4]
Any thoughts about making this project asynchronous? It would be great to be able to `await` with this library.

**Comment by Francessco121** [comment]
Due to how .NET handles asynchronous code, this would cause issues with some internal pieces of Discore, mainly just causing extra overhead. However, we definitely could provide asynchronous methods for things interacting directly with Discord's HTTP API.

Currently we are in the process of rewriting the library as a whole on the v2 branch, we may include this in the initial v2 release.
