### ISSUE TITLE
Creation date account

### ISSUE THREAD

**Issue by SunnyElite** [BundledSticksInkorperated/Discore#40]
Hi, I know that I already created a similar topic, and it was said that it is impossible to implement, but at that time I did not remember where I saw it, now I found it. DSharpPlus has User has the object CreationTimestamp, with which you can get the date of creation of the account, the examples below.

`DateTime CreationDate = discord.GetUserAsync(123456).GetAwaiter().GetResult().CreationTimestamp.Date;
`
In the end, we get the date -

![image](https://user-images.githubusercontent.com/28116659/32908944-3d69de8c-cb16-11e7-923e-72e0fd9199c6.png)

Try it now :)

**Comment by Francessco121** [comment]
Interesting! DSharpPlus is actually grabbing this timestamp off of the user's ID...which they apply to every entity. See: [https://github.com/NaamloosDT/DSharpPlus/blob/master/DSharpPlus/Entities/SnowflakeObject.cs](https://github.com/NaamloosDT/DSharpPlus/blob/master/DSharpPlus/Entities/SnowflakeObject.cs)

I had completely forgot that the ID's contain this information. You can actually get a user's creation date in Discore currently then. Create a `Snowflake` instance around their ID (if you don't already have it as a Snowflake). Then call `GetTimestamp()`. You can either use the `Snowflake` constructor or actually cast a `ulong` to a `Snowflake` to access the method. [This is the method I'm talking about](https://github.com/BundledSticksInkorperated/Discore/blob/master/src/Discore/Snowflake.cs#L31).

So for example if you don't just have the raw number and have a user object instead:
```csharp
DiscordUser someUser;
DateTime creationDate = someUser.Id.GetTimestamp();
```

Sorry for closing your previous issue, it's been a long time since I wrote the `Snowflake` file. :)

**Comment by SunnyElite** [comment]
Yes, thanks )
