### ISSUE TITLE
User token support?

### ISSUE THREAD

**Issue by DylanFPS** [BundledSticksInkorperated/Discore#49]
We're interested in using Discore as a discord client library for Users, not bots. Is this possible in the current version?

**Comment by teh-random-name** [comment]
Currently this is not possible, Discord's API is only for use with bots, user authentication isn't publicly documents nor supported.

**Comment by DylanFPS** [comment]
Huh, Discord.Net seems to have support for it.

**Comment by DylanFPS** [comment]
And the authentication flow is documented, we have implemented a system which acquires the user token.

**Comment by Francessco121** [comment]
To elaborate on this a little more: the Discord developers have stated that their API is intended only for bots as of about a year ago. While technically you *can* authenticate as a user and use the documented API bits to make a basic client, it's not meant to be used this way.

We're just trying to respect this by keeping Discore under the scope of bot applications.

If their stance on this has changed recently, please correct me however.

**Comment by Francessco121** [comment]
I do understand that some of the other .NET Discord libraries support normal user authentication, however those libraries were around before Discord stated that they only wish to support proper bots. Discore was a little late to the party, so we decided to only support bots.

**Comment by Francessco121** [comment]
Apologies for splitting this into so many comments.

I should clear up my explanation here. Yes, you can use some of the API via normal OAuth. There are some things supported by Discord. I had forgotten about that. However, it's only a handful of HTTP endpoints. [As noted here](https://discordapp.com/developers/docs/topics/oauth2#bot-vs-user-accounts), only bots are allowed to use WebSocket API, which Discore heavily focuses on. Since only a very small subset of the HTTP API is meant for non-bots, Discore opt-ed out for supporting it.

Sorry for any confusion about our stance.
