### ISSUE TITLE
Getting the role of an user?

### ISSUE THREAD

**Issue by kitsun8** [BundledSticksInkorperated/Discore#53]
Hello! I'm trying to get the name of roles for the user sending a command to the bot.
I'd love to put out some code but I'm stumped right at the beginning. Of course, I can get the ID of the message author and so, but other than that, I'm at loss. Any advice? Tried looking up the documentation, but didn't find hits there.

Thank you!

**Comment by Francessco121** [comment]
Sorry for the lack of documentation on that.

In order to get the names of every role the user has, you'll need to retrieve two objects: the guild and the guild member. Make sure you also have a `DiscordHttpClient` instance available, since you may need to fallback on HTTP requests to get this data if it's not cached.

First, you'll want to get the actual `DiscordChannel` that the message was retrieved from:
```csharp
// Try and get the channel from the cache first, this will return null if it's not available.
// The `shard` instance is available from the event data for the message event.
DiscordChannel channel = shard.Cache.GetChannel(message.ChannelId);

// Fallback to the HTTP API if it wasn't cached 
// (99% of the time this won't be needed, but theoretically it could be).
if (channel == null)
    channel = await http.GetChannel(message.ChannelId);
```

After you have the channel object, you'll want to ensure that it's a guild text channel (if you can't already assume this). The type can be checked with `channel.ChannelType`. Once you know it's a guild channel, you'll need to get the guild object and the guild member of the message author:
```csharp
// First, cast the channel to a guild channel so the guild ID can be retrieved.
DiscordGuildTextChannel textChannel = (DiscordGuildTextChannel)channel;

// Try getting the guild from cache
DiscordGuild guild = shard.Cache.GetGuild(textChannel.GuildId);

// Fallback to HTTP API if needed
if (guild == null)
    guild = await http.GetGuild(textChannel.GuildId);

// Try getting the guild member from cache
DiscordGuildMember member = shard.Cache.GetGuildMember(textChannel.GuildId, message.Author.Id);

// Fallback to HTTP API if needed
if (member == null)
    member = await http.GetGuildMember(textChannel.GuildId, message.Author.Id);
```

At this point, you now have a dictionary of all roles in the guild (`guild.Roles`) and a list of IDs for each role the user has (`member.RoleIds`). From here you can now get the full `DiscordRole` objects that the user has:

```csharp
// Simply map the IDs from the member to the full role objects.
var roles = new List<DiscordRole>();

foreach (Snowflake roleId in member.RoleIds)
    roles.Add(guild.Roles[roleId]);
```

After that, you can access the names of each role through their `Name` property. If you're just looking for one role, you could also skip the list and just check each role as you map them in the loop.

Unfortunately, to avoid making HTTP calls as much as possible, the code really is that verbose. If you're not really in danger of being rate limited by the HTTP API (meaning this code doesn't run too often), you could simplify this and only use the HTTP API:
```csharp
// Make sure you can guarantee that channel ID is for a guild text channel!
// You may want to use the non generic overload and just get a normal channel back
// and check the type before casting, the generic overload casts it for you.
DiscordGuildTextChannel textChannel = 
    await http.GetChannel<DiscordGuildTextChannel>(message.ChannelId);

// Get the guild roles directly without a guild object
IReadOnlyList<DiscordRole> roles =
    await http.GetGuildRoles(textChannel.GuildId);

// Get the guild member
DiscordGuildMember member =
    await http.GetGuildMember(textChannel.GuildId, message.Author.Id);
```

From there, it's a pretty similar situation of just lining up the role IDs from the member with the roles from the guild.

Hope this helps! :)

**Comment by kitsun8** [comment]
Thank you! This was very helpful :)
