### ISSUE TITLE
Help adding a role to a specific Member?

### ISSUE THREAD

**Issue by ddolpali** [BundledSticksInkorperated/Discore#6]
I looked over the library and noticed that you can add a role to a user through the DiscordGuildMember. However, I'm not able to grab the object.

I have tried the following, but I am still unable to cast the cached member as a DiscordGuildMember.
```csharp
DiscordMessage message = e.Message;
DiscoreCache cache = e.Shard.Cache;
DiscordGuildTextChannel guildTextChannel = cache.Channels.Get(message.ChannelId) as DiscordGuildTextChannel;
DiscoreGuildCache guildCache = cache.Guilds.Get(guildTextChannel.GuildId);
DiscordGuildMember member = (DiscordGuildMember)guildCache.Members.Get(e.Message.Author.Id));
```

Thanks,
ddolpali

**Comment by Francessco121** [comment]
`guildCache.Members.Get` actually returns a `DiscoreMemberCache` object, to get the actual member object just use the `Value` property on the result.

So changing the last line to:
```csharp
DiscordGuildMember member = guildCache.Members.Get(e.Message.Author.Id).Value;
```
should do the trick.

**Comment by ddolpali** [comment]
Ah, thank you! It seems to be working properly :)

Are there any plans for shortening classes? Having to type one big line/multiple ones for a command seems to be impractical imo (though it's probably a bigger pain for me since I have a file per command).

Thanks

**Comment by teh-random-name** [comment]
Glad you got it working!

To my knowledge there isn't any plan on shortening classes, but this may change based on feedback of course.
I'll speak to @Francessco121 about this in the morning and see if it's something possible down the line.

**Comment by Francessco121** [comment]
In the future (I'm hoping to do this for 3.0) I do want to simplify the cache and make it more consistent.

For now however, you may be able to shorten that code by just using the HTTP API instead of going through the cache (this is if you don't need details about the member). `DiscordGuildMember.AddRole` is just a shortcut to the HTTP method.

I do agree though, getting important information for processing commands is a bit bulky (ran into this with my personal bot).
