### ISSUE TITLE
Possibly missing references in NuGet package

### ISSUE THREAD

**Issue by kitsunen** [BundledSticksInkorperated/Discore#8]
Hi! Just wanted to bring this up, might be nothing:
![image](https://cloud.githubusercontent.com/assets/6533970/25084978/53ecd3ea-2368-11e7-97d2-a1297ac6bfbf.png)

I was trying to put Discore into a C# Console Application, using .NET Framework 4.6.1 (Should be compatible with Standard 1.6 according to https://docs.microsoft.com/en-us/dotnet/articles/standard/library#net-platforms-support (sidenote, "with tooling 2.0", whatever that means), and got this error with Package Manager. Using VS 2017 with every module installed with current updates.

I'll be using .Net Core for now, but if this is a bug, you should know about it :) 👍 Thanks for your hard work!

**Comment by Francessco121** [comment]
Thanks for bringing this to my attention!

My understanding of .NET Standard was that if any other target supported the .NET Standard version, it would be able to just simply reference it (for instance, .NET Core applications just kinda work with it). That "tooling 2.0" bit is actually new since the last time I've looked. I'm not actually sure what that means because I can't even link a 4.6.1 project and Discore outside of NuGet in VS 2017, nor can I find any information on ".NET Framework tooling 2.0".

It seems that one possible reason it won't allow this currently is because of Discore's dependencies. After telling Discore to target both .NET Standard 1.6 and framework 4.6.1, I had to actually add more .NET related NuGet packages (things like HttpClient weren't included in pure 4.6.1). Which to me, makes no sense that .NET Standard 1.6 includes it out-of-the-box, yet they say 4.6.1 implements standard 1.6 and it doesn't include it... 😕 

That said, with those minor changes, to just the project file, I did get this work and I can release a patch today for it. I may actually release it as 2.3.0 since I do have new features (not all of the ones I wanted to include in 2.3.0 but I understand this is important).

If you find out any more information on this, I'd love to hear it!

**Comment by Francessco121** [comment]
Would you mind giving the patch/2.2.1 branch a try? Everything seems to work on my end, but I would just like to make sure I solved your issue before I release it.

**Comment by Francessco121** [comment]
So after doing a little more research, it seems that this "tooling 2.0" thing isn't actually released yet. Once it is, Discore in its current state should work just fine with framework 4.6.1. If you don't need full framework support just yet, I would like to avoid targeting two different frameworks. 

The current "fix" on the patch/2.2.1 branch may behave differently since the actual .NET implementation for things like WebSockets are different.

**Comment by kitsunen** [comment]
Yeah, I figured that it might not exist, given the lack of hits on searches. I am completely content with .NET core, so no, you don't need to do anything just now. :) It would be a hack to make it work unofficially either way, with no official support yet.

The only reason I found out this was because I had a console application on .NET Framework 4.6.1 that had some ready functions that I required. Since then, I've ported those to .NET core :)

Thanks for looking into this, let's take another look at it when actual support is ready.
