### ISSUE TITLE
How to get the voice channel

### ISSUE THREAD

**Issue by SunnyElite** [BundledSticksInkorperated/Discore#9]
How to get the voice channel for DiscordGuildVoiceChannel voiceChannel = ...;
What do I need to do after the dots?

**Comment by Francessco121** [comment]
There are three ways to grab a voice channel. Preferably you would want to go with one of the cache solutions (to avoid HTTP rate limits). As for which cache-based solution, that entirely depends on what information you need. If you are looking for a list of members in this voice channel, you will need to use the "guild cache" solution since the list is stored in the cache version of the voice channel (i.e. `DiscoreVoiceChannelCache`).

### From Cache
Assuming you have a `DiscoreCache` variable named `cache` and the ID of the voice channel named `channelId`:
```csharp
DiscordGuildVoiceChannel voiceChannel = cache.Channels[channelId] as DiscordGuildVoiceChannel;
// If voiceChannel is null here then, the channel does not exist or it was not a voice channel
```

### From Guild Cache
Assuming you have a `DiscoreGuildCache` variable named `guildCache` and the ID of the voice channel named `channelId`:
```csharp
// Get a reference to the cache of the voice channel itself
DiscoreVoiceChannelCache channelCache = guildCache.VoiceChannels[channelId];

// Get a snapshot of the actual channel
DiscordGuildVoiceChannel voiceChannel = channelCache.Value;
```

### From HTTP
Assuming you have an `DiscordHttpApi` variable named `http` and the ID of the voice channel named `channelId`:
```csharp
// Beware: this will throw a cast exception if channelId didn't point to a voice channel
DiscordGuildVoiceChannel voiceChannel = await http.Channels.Get<DiscordGuildVoiceChannel>(channelId);
```

**Comment by SunnyElite** [comment]
It's good, it works.
But here's how to get channelId?
I did not find the documentation for this, but to sit guessing that I did not want to.

**Comment by Francessco121** [comment]
Where the channel ID comes from would depend on the situation. What are you trying to do that requires a voice channel? Is this in response to a user's message or...?

**Comment by SunnyElite** [comment]
I want to make music playback in the voice channel.
From the .mp3 file for example

**Comment by Francessco121** [comment]
Ok, but how will the bot join the channel? Will a user ask it to join the channel they are in, or will the user give your bot the name of the channel?

**Comment by SunnyElite** [comment]
![image](https://cloud.githubusercontent.com/assets/28116659/25854351/5ac90bd0-34d8-11e7-9c7f-74fdb89669a7.png)
No difference, or that the user called him by the team, or he himself went into the channel that is set.

**Comment by Francessco121** [comment]
Sorry for the late reply!

There would be a actually difference. If a user joins a voice channel and then asks the bot to join them, you can get the voice channel ID right off of the user's voice state. Versus, if the user gave the bot the name of the voice channel to join, you would need to go through each voice channel in the guild's cache until you find it by name (here you wouldn't even need the ID).

I'm going to need a little bit more context to help you...
